"""Persistence and adapter ports exclusive to the teacher-aligned Proxy."""

from __future__ import annotations

from collections.abc import Callable
from typing import Protocol

from .contracts import PaperSearchV01Request, ProxyCapabilityToken, ProxyOperation


class ProxyRepository(Protocol):
    def add_token(self, token: ProxyCapabilityToken) -> None: ...
    def find_token_by_digest(self, digest: str) -> ProxyCapabilityToken | None: ...
    def get_token(self, token_id: str, *, for_update: bool = False) -> ProxyCapabilityToken | None: ...
    def save_token(self, token: ProxyCapabilityToken) -> None: ...
    def get_operation(self, operation_id: str) -> ProxyOperation | None: ...
    def find_by_idempotency(self, token_id: str, idempotency_key: str) -> ProxyOperation | None: ...
    def add_operation(self, operation: ProxyOperation) -> None: ...
    def save_operation(self, operation: ProxyOperation) -> None: ...
    def count_active(self, token_id: str) -> int: ...
    def reconcile_running(self, evidence: str) -> int: ...


class ProxyUnitOfWork(Protocol):
    proxy: ProxyRepository
    def __enter__(self) -> ProxyUnitOfWork: ...
    def __exit__(self, exc_type, exc, traceback) -> None: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...


ProxyUnitOfWorkFactory = Callable[[], ProxyUnitOfWork]


class PaperSearchAdapter(Protocol):
    adapter_id: str
    invocation_count: int
    def search(self, request: PaperSearchV01Request) -> dict: ...
