import type {
  Approval,
  ExecutionEvent,
  WorkflowDefinition,
  WorkflowRun,
} from "@/types/api";

export const workflowFixture: WorkflowDefinition = {
  id: "literature-review",
  version: "1.0.0",
  name: "Literature review",
  schema_version: "reagent/v1alpha1",
  input_schema: { query: { type: "string", required: true } },
  outputs: { summary: "${nodes.summary.outputs.summary}" },
  steps: [
    {
      id: "search",
      kind: "skill",
      needs: [],
      uses: "mock_paper_search@1.0.0",
      input_mapping: { query: "${inputs.query}" },
      timeout_seconds: 300,
      max_attempts: 1,
      approval_policy: null,
    },
    {
      id: "summary",
      kind: "skill",
      needs: ["search"],
      uses: "mock_summary@1.0.0",
      input_mapping: { papers: "${nodes.search.outputs.papers}" },
      timeout_seconds: 300,
      max_attempts: 1,
      approval_policy: null,
    },
  ],
};

export const runFixture: WorkflowRun = {
  id: "run-123456789",
  project_id: "project-1",
  workflow_id: "literature-review",
  workflow_version: "1.0.0",
  actor_user_id: "user-1",
  agent_session_id: "agent-1",
  status: "WAITING_FOR_APPROVAL",
  inputs: { query: "persistent research agents" },
  outputs: {},
  wait_reason: "approval:approve_sources",
  error_code: null,
  completed_steps: ["search"],
  checkpoint_count: 5,
  created_at: "2026-07-21T08:00:00Z",
  updated_at: "2026-07-21T08:05:00Z",
  steps: [
    {
      id: "step-1",
      step_id: "search",
      attempt: 1,
      status: "COMPLETED",
      inputs: {},
      outputs: { papers: [] },
      error_code: null,
      created_at: "2026-07-21T08:00:00Z",
      updated_at: "2026-07-21T08:02:00Z",
    },
    {
      id: "step-2",
      step_id: "approve_sources",
      attempt: 1,
      status: "WAITING_APPROVAL",
      inputs: {},
      outputs: {},
      error_code: null,
      created_at: "2026-07-21T08:00:00Z",
      updated_at: "2026-07-21T08:05:00Z",
    },
  ],
};

export const eventsFixture: ExecutionEvent[] = [
  {
    id: "event-1",
    sequence: 1,
    type: "WORKFLOW_STARTED",
    severity: "INFO",
    payload: { status: "RUNNING" },
    timestamp: "2026-07-21T08:00:00Z",
    agent_session_id: "agent-1",
    step_run_id: null,
    correlation_id: "run-1",
    causation_id: null,
  },
  {
    id: "event-2",
    sequence: 2,
    type: "STEP_STARTED",
    severity: "INFO",
    payload: { step_id: "search" },
    timestamp: "2026-07-21T08:01:00Z",
    agent_session_id: "agent-1",
    step_run_id: "step-1",
    correlation_id: "run-1",
    causation_id: null,
  },
];

export const approvalFixture: Approval = {
  id: "approval-1",
  project_id: "project-1",
  workflow_run_id: "run-123456789",
  step_run_id: "step-2",
  policy_key: "project_reviewer",
  request_fingerprint: "sha256:fixture",
  prompt: "Approve the selected sources before synthesis",
  requested_action: { step_id: "approve_sources", workflow_version: "1.0.0" },
  requested_by: "agent-1",
  permitted_approver_role: "project_reviewer",
  requested_at: "2026-07-21T08:05:00Z",
  expires_at: "2026-07-22T08:05:00Z",
  status: "PENDING",
  resolved_by: null,
  resolved_at: null,
  decision_reason: null,
};
