import type {
  Approval,
  ExecutionEvent,
  WorkflowDefinition,
  WorkflowRun,
  LocalProject,
  UploadedProgressReport,
} from "@/types/api";

export const workflowFixture: WorkflowDefinition = {
  id: "literature-review",
  version: "1.0.0",
  name: "Literature review",
  schema_version: "reagent/v1alpha1",
  input_schema: { query: { type: "string", required: true } },
  outputs: { summary: "${nodes.summary.outputs.summary}" },
  steps: [
    {
      id: "search",
      kind: "skill",
      needs: [],
      uses: "mock_paper_search@1.0.0",
      input_mapping: { query: "${inputs.query}" },
      timeout_seconds: 300,
      max_attempts: 1,
      approval_policy: null,
    },
    {
      id: "summary",
      kind: "skill",
      needs: ["search"],
      uses: "mock_summary@1.0.0",
      input_mapping: { papers: "${nodes.search.outputs.papers}" },
      timeout_seconds: 300,
      max_attempts: 1,
      approval_policy: null,
    },
  ],
};

export const runFixture: WorkflowRun = {
  id: "run-123456789",
  project_id: "project-1",
  workflow_id: "literature-review",
  workflow_version: "1.0.0",
  actor_user_id: "user-1",
  agent_session_id: "agent-1",
  status: "WAITING_FOR_APPROVAL",
  inputs: { query: "persistent research agents" },
  outputs: {},
  wait_reason: "approval:approve_sources",
  error_code: null,
  completed_steps: ["search"],
  checkpoint_count: 5,
  created_at: "2026-07-21T08:00:00Z",
  updated_at: "2026-07-21T08:05:00Z",
  steps: [
    {
      id: "step-1",
      step_id: "search",
      attempt: 1,
      status: "COMPLETED",
      inputs: {},
      outputs: { papers: [] },
      error_code: null,
      created_at: "2026-07-21T08:00:00Z",
      updated_at: "2026-07-21T08:02:00Z",
    },
    {
      id: "step-2",
      step_id: "approve_sources",
      attempt: 1,
      status: "WAITING_APPROVAL",
      inputs: {},
      outputs: {},
      error_code: null,
      created_at: "2026-07-21T08:00:00Z",
      updated_at: "2026-07-21T08:05:00Z",
    },
  ],
};

export const eventsFixture: ExecutionEvent[] = [
  {
    id: "event-1",
    sequence: 1,
    type: "WORKFLOW_STARTED",
    severity: "INFO",
    payload: { status: "RUNNING" },
    timestamp: "2026-07-21T08:00:00Z",
    agent_session_id: "agent-1",
    step_run_id: null,
    correlation_id: "run-1",
    causation_id: null,
  },
  {
    id: "event-2",
    sequence: 2,
    type: "STEP_STARTED",
    severity: "INFO",
    payload: { step_id: "search" },
    timestamp: "2026-07-21T08:01:00Z",
    agent_session_id: "agent-1",
    step_run_id: "step-1",
    correlation_id: "run-1",
    causation_id: null,
  },
];

export const approvalFixture: Approval = {
  id: "approval-1",
  project_id: "project-1",
  workflow_run_id: "run-123456789",
  step_run_id: "step-2",
  policy_key: "project_reviewer",
  request_fingerprint: "sha256:fixture",
  prompt: "Approve the selected sources before synthesis",
  requested_action: { step_id: "approve_sources", workflow_version: "1.0.0" },
  requested_by: "agent-1",
  permitted_approver_role: "project_reviewer",
  requested_at: "2026-07-21T08:05:00Z",
  expires_at: "2026-07-22T08:05:00Z",
  status: "PENDING",
  resolved_by: null,
  resolved_at: null,
  decision_reason: null,
};

export const localProjectFixture: LocalProject = {
  project_id: "project-0123456789abcdef0123456789abcdef",
  name: "Fictional local continuity review",
  research_topic: "A fictional public topic about portable research folders",
  selected_workflow: "LITERATURE_SEARCH",
  created_at: "2026-08-05T08:00:00Z",
  updated_at: "2026-08-05T08:05:00Z",
  current_package: {
    package_id: "literature-search-project-0123456789abcdef0123456789abcdef-v0.2",
    package_schema_version: "workflow-package/v0.1",
    package_checksum: `sha256:${"a".repeat(64)}`,
    manifest_checksum: `sha256:${"b".repeat(64)}`,
    zip_checksum: `sha256:${"c".repeat(64)}`,
    workflow_id: "literature-search-local-experimental",
    workflow_version: "0.1.0",
    workflow_checksum: `sha256:${"d".repeat(64)}`,
    file_count: 30,
    package_size_bytes: 24000,
    generated_at: "2026-08-05T08:05:00Z",
    download_url: "/projects/project-0123456789abcdef0123456789abcdef/packages/example/download",
  },
  progress: {
    schema_version: "project-progress-projection/v0.1",
    project_id: "project-0123456789abcdef0123456789abcdef",
    package_id: "literature-search-project-0123456789abcdef0123456789abcdef-v0.2",
    package_schema_version: "workflow-package/v0.1",
    package_checksum: `sha256:${"a".repeat(64)}`,
    workflow_id: "literature-search-local-experimental",
    workflow_version: "0.1.0",
    latest_accepted_report_id: `prv2-${"e".repeat(64)}`,
    latest_accepted_report_checksum: `sha256:${"f".repeat(64)}`,
    latest_execution_round: 1,
    latest_status: "COMPLETED",
    completed_work_summary: [
      "Queries performed: 2",
      "Candidates retained: 8",
      "Papers selected: 4",
      "Outputs generated: 4",
    ],
    current_state_summary: "Selection rationale is ready for review.",
    next_recommended_action: "Review the local report.",
    output_artifacts: [{
      relative_path: "outputs/search_plan.md",
      artifact_kind: "SEARCH_PLAN",
      media_type: "text/markdown",
      checksum: `sha256:${"1".repeat(64)}`,
      size: 128,
    }],
    warning_count: 2,
    error_count: 1,
    unresolved_question_count: 0,
    harness_type: "codex",
    latest_local_execution_timestamp: "2026-08-05T08:04:00Z",
    latest_upload_timestamp: "2026-08-05T08:05:00Z",
    chain_state: "VALID_CHAIN",
    legacy_warning_state: false,
    projection_checksum: `sha256:${"2".repeat(64)}`,
  },
};

export const progressReportFixture: UploadedProgressReport = {
  receipt_id: "progress-receipt-fictional",
  project_id: localProjectFixture.project_id,
  package_id: localProjectFixture.current_package!.package_id,
  package_checksum: localProjectFixture.current_package!.package_checksum,
  report_id: localProjectFixture.progress!.latest_accepted_report_id,
  report_checksum: localProjectFixture.progress!.latest_accepted_report_checksum,
  report_schema_version: "progress-report/v0.2",
  original_report_checksum: `sha256:${"3".repeat(64)}`,
  original_report_size: 2048,
  original_report_media_type: "application/json",
  envelope_checksum: `sha256:${"4".repeat(64)}`,
  uploaded_at: "2026-08-05T08:05:00Z",
  received_at: "2026-08-05T08:05:01Z",
  uploader_type: "local-cli",
  client_version: "fictional-client/0.2.0",
  source_path_hint: "memory/progress/reports/round-2.json",
  validation_status: "ACCEPTED",
  validation_errors: [],
  validation_warnings: [],
  chain_state: "VALID_CHAIN",
  accepted_for_projection: true,
  normalized_record: {
    report_id: localProjectFixture.progress!.latest_accepted_report_id,
    execution_round: 1,
    status: "COMPLETED",
    completed_work: localProjectFixture.progress!.completed_work_summary,
    current_state: "Selection rationale is ready for review.",
    next_recommended_action: "Review the local report.",
    output_artifacts: localProjectFixture.progress!.output_artifacts,
    warnings: [
      "Fictional warning for owner review.",
      "Metadata and abstract-only evidence; no full text was read.",
    ],
    errors: ["Fictional recoverable report error."],
    unresolved_questions: [],
  },
};
